# Generated by Django 3.2.2 on 2021-05-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Str_obj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('img_obj', models.ImageField(upload_to='img_obj')),
            ],
        ),
    ]
