# Generated by Django 3.2.2 on 2021-05-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fstr', '0002_str_obj_files_ls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='str_obj',
            name='files_ls',
        ),
    ]
