# Generated by Django 3.2.2 on 2021-05-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fstr', '0014_alter_str_obj_img_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='str_obj',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
