# Generated by Django 3.2.2 on 2021-05-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fstr', '0015_alter_str_obj_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='str_obj',
            name='files_ls',
            field=models.FileField(default='some text', upload_to='documents/'),
        ),
    ]
