# Generated by Django 3.2.2 on 2021-05-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fstr', '0016_str_obj_files_ls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='str_obj',
            name='files_ls',
            field=models.FileField(default='some text', upload_to='documents'),
        ),
    ]
